#!/usr/bin/env python3
"""Generate the research figures and displayed formulas used by the homepage.

The figures are not decorative reconstructions.

1. The Crouzeix figure is the sharpness example stated in the manuscript:
   N = [[0, 2], [0, 0]], p(z) = z, and W(N) is the closed unit disk.
   Its boundary is drawn from the exact parametrization exp(i theta).
2. The Hatano-Nelson figure samples
   s_min(z I_n - A_n(a)), A_n(a) = tridiag(a, 0, 1), on a stated Cartesian
   grid for the manuscript parameters a = 1/4 and epsilon = 10^-2.

All mathematical labels are typeset by the local LaTeX installation.
Computer Modern is used for the Crouzeix material, matching that manuscript.
Latin Modern is used for the Hatano-Nelson material, matching that manuscript.

Run from the repository root with the environment documented in README.md:

    conda run -n wirtinger_calculus python scripts/generate_research_figures.py
"""

from __future__ import annotations

import json
import platform
import subprocess
import tempfile
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import scipy
from scipy.optimize import minimize_scalar


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)

INK = "#17211e"
INK_SOFT = "#46514c"
PAPER = "#fffdf8"
TEAL = "#166a64"
TEAL_LIGHT = "#a8d8d0"
CORAL = "#d85f42"

A_VALUE = 0.25
EPSILON = 1.0e-2
GRID_X = np.linspace(-1.12, 1.12, 561)
GRID_Y = np.linspace(-0.30, 0.30, 361)


def latex_style(*, latin_modern: bool) -> dict[str, object]:
    """Return a Matplotlib style that delegates every text glyph to LaTeX."""
    preamble = r"\usepackage{amsmath,amssymb}"
    if latin_modern:
        preamble = r"\usepackage{lmodern}" + preamble
    return {
        "text.usetex": True,
        "text.latex.preamble": preamble,
        "font.family": "serif",
        "font.size": 10.0,
        "axes.labelsize": 10.0,
        "axes.titlesize": 10.0,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 8.5,
        "ytick.labelsize": 8.5,
        "axes.linewidth": 0.7,
        "lines.linewidth": 1.2,
        "xtick.major.width": 0.7,
        "ytick.major.width": 0.7,
        "savefig.facecolor": PAPER,
        "figure.facecolor": PAPER,
    }


def save_png(fig: mpl.figure.Figure, filename: str) -> None:
    fig.savefig(
        ASSETS / filename,
        dpi=240,
        bbox_inches="tight",
        pad_inches=0.06,
        facecolor=PAPER,
        metadata={
            "Software": (
                f"Python {platform.python_version()}; "
                f"NumPy {np.__version__}; Matplotlib {mpl.__version__}"
            ),
            "Description": "Generated by scripts/generate_research_figures.py",
        },
    )
    plt.close(fig)


def crouzeix_sharpness_figure() -> None:
    """Draw the exact sharpness example from the Crouzeix manuscript."""
    theta = np.linspace(0.0, 2.0 * np.pi, theta_sample_count())
    boundary = np.exp(1j * theta)

    with plt.rc_context(latex_style(latin_modern=False)):
        fig = plt.figure(figsize=(8.2, 4.15))
        grid = fig.add_gridspec(1, 2, width_ratios=(0.92, 1.08), wspace=0.18)
        ax = fig.add_subplot(grid[0, 0])
        statement = fig.add_subplot(grid[0, 1])

        ax.fill(
            boundary.real,
            boundary.imag,
            facecolor=TEAL_LIGHT,
            alpha=0.42,
            edgecolor="none",
        )
        ax.plot(
            boundary.real,
            boundary.imag,
            color=TEAL,
            label=r"$\partial W(N)$",
        )
        ax.plot(
            [0.0],
            [0.0],
            marker="x",
            color=CORAL,
            markersize=7.0,
            markeredgewidth=1.4,
            linestyle="none",
            label=r"$\sigma(N)=\{0\}$",
        )
        ax.axhline(0.0, color=INK_SOFT, linewidth=0.55, zorder=0)
        ax.axvline(0.0, color=INK_SOFT, linewidth=0.55, zorder=0)
        ax.set_xlim(-1.18, 1.18)
        ax.set_ylim(-1.18, 1.18)
        ax.set_aspect("equal")
        ax.set_xlabel(r"$\operatorname{Re} z$")
        ax.set_ylabel(r"$\operatorname{Im} z$")
        ax.set_xticks([-1.0, 0.0, 1.0])
        ax.set_yticks([-1.0, 0.0, 1.0])
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.legend(
            loc="lower center",
            bbox_to_anchor=(0.5, 1.03),
            ncol=2,
            frameon=False,
            borderaxespad=0.0,
        )

        statement.axis("off")
        statement.text(
            0.02,
            0.87,
            r"\textsc{Sharpness example}",
            color=INK_SOFT,
            fontsize=9.0,
            transform=statement.transAxes,
        )
        statement.text(
            0.02,
            0.66,
            r"$N=\begin{pmatrix}0&2\\[2pt]0&0\end{pmatrix},"
            r"\qquad p(z)=z$",
            color=INK,
            fontsize=17.0,
            transform=statement.transAxes,
        )
        statement.text(
            0.02,
            0.43,
            r"$W(N)=\{z\in\mathbb{C}:|z|\leq 1\}$",
            color=INK,
            fontsize=15.0,
            transform=statement.transAxes,
        )
        statement.text(
            0.02,
            0.19,
            r"$\|p(N)\|=2"
            r"=2\max_{z\in W(N)}|p(z)|$",
            color=INK,
            fontsize=15.0,
            transform=statement.transAxes,
        )

        save_png(fig, "crouzeix-sharpness.png")


def hatano_matrix(n: int, a: float) -> np.ndarray:
    """Return A_n(a) = tridiag(a, 0, 1)."""
    matrix = np.zeros((n, n), dtype=float)
    index = np.arange(n - 1)
    matrix[index, index + 1] = 1.0
    matrix[index + 1, index] = a
    return matrix


def hatano_eigenvalues(n: int, a: float) -> np.ndarray:
    """Return the exact open-boundary eigenvalues in increasing order."""
    k = np.arange(1, n + 1)
    return np.sort(2.0 * np.sqrt(a) * np.cos(k * np.pi / (n + 1)))


def least_singular_value_grid(n: int, a: float) -> np.ndarray:
    """Sample s_min(z I_n - A_n(a)) on the declared Cartesian grid."""
    matrix = hatano_matrix(n, a)
    identity = np.eye(n)
    values = np.empty((GRID_Y.size, GRID_X.size), dtype=float)
    for row, imaginary_part in enumerate(GRID_Y):
        z = GRID_X + 1j * imaginary_part
        pencils = z[:, None, None] * identity[None, :, :] - matrix[None, :, :]
        values[row] = np.linalg.svd(pencils, compute_uv=False)[:, -1]
    return values


def gamma_estimate(n: int, a: float) -> tuple[float, float]:
    """Estimate gamma_n by bounded optimization in every spectral gap."""
    matrix = hatano_matrix(n, a)
    identity = np.eye(n)
    eigenvalues = hatano_eigenvalues(n, a)

    def smin_real(x: float) -> float:
        return float(np.linalg.svd(x * identity - matrix, compute_uv=False)[-1])

    maxima: list[tuple[float, float]] = []
    for left, right in zip(eigenvalues[:-1], eigenvalues[1:]):
        trial_x = np.linspace(left, right, 121)
        trial_y = np.array([smin_real(x) for x in trial_x])
        index = int(np.argmax(trial_y))
        lower = trial_x[max(0, index - 1)]
        upper = trial_x[min(trial_x.size - 1, index + 1)]
        result = minimize_scalar(
            lambda x: -smin_real(float(x)),
            bounds=(float(lower), float(upper)),
            method="bounded",
            options={"xatol": 5.0e-14, "maxiter": 250},
        )
        if not result.success:
            raise RuntimeError(f"Gap optimization failed for n={n}")
        optimized = (smin_real(float(result.x)), float(result.x))
        sampled = (float(trial_y[index]), float(trial_x[index]))
        maxima.append(max(optimized, sampled, key=lambda pair: pair[0]))
    return max(maxima, key=lambda pair: pair[0])


def hatano_transition_figure() -> dict[str, dict[str, float]]:
    """Draw two manuscript-parameter pseudospectral samples."""
    estimates: dict[str, dict[str, float]] = {}

    with plt.rc_context(latex_style(latin_modern=True)):
        fig, axes = plt.subplots(
            1,
            2,
            figsize=(8.2, 3.85),
            sharex=True,
            sharey=True,
            constrained_layout=True,
        )

        for panel, (ax, n) in enumerate(zip(axes, (6, 7))):
            values = least_singular_value_grid(n, A_VALUE)
            gamma_value, gamma_location = gamma_estimate(n, A_VALUE)
            estimates[str(n)] = {
                "gamma_estimate": gamma_value,
                "maximizing_x_estimate": gamma_location,
            }

            ax.contourf(
                GRID_X,
                GRID_Y,
                values,
                levels=[-1.0, EPSILON],
                colors=[TEAL_LIGHT],
                alpha=0.78,
            )
            ax.contour(
                GRID_X,
                GRID_Y,
                values,
                levels=[EPSILON],
                colors=[TEAL],
                linewidths=1.25,
            )
            eigenvalues = hatano_eigenvalues(n, A_VALUE)
            ax.plot(
                eigenvalues,
                np.zeros(n),
                "x",
                color=CORAL,
                markersize=5.0,
                markeredgewidth=1.2,
            )
            ax.axhline(0.0, color=INK_SOFT, linewidth=0.5, zorder=0)
            relation = ">" if gamma_value > EPSILON else "<"
            component_text = (
                "six sampled components" if n == 6 else "one sampled component"
            )
            ax.set_title(
                rf"$n={n}$: {component_text}"
                + "\n"
                + rf"$\widehat{{\gamma}}_{n}={gamma_value:.4f}"
                + rf"\ {relation}\ \varepsilon$",
                pad=8,
            )
            ax.set_xlabel(r"$\operatorname{Re} z$")
            if panel == 0:
                ax.set_ylabel(r"$\operatorname{Im} z$")
            ax.set_xlim(float(GRID_X[0]), float(GRID_X[-1]))
            ax.set_ylim(float(GRID_Y[0]), float(GRID_Y[-1]))
            ax.set_xticks([-1.0, -0.5, 0.0, 0.5, 1.0])
            ax.set_yticks([-0.25, 0.0, 0.25])
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)

        fig.suptitle(
            r"$A_n(a)=\operatorname{tridiag}(a,0,1),"
            r"\quad a=\frac14,\quad \varepsilon=10^{-2}$",
            color=INK,
            fontsize=11.0,
        )
        save_png(fig, "hatano-transition.png")

    return estimates


def render_formula_svg(
    filename: str,
    formula: str,
    *,
    latin_modern: bool,
) -> None:
    """Typeset one formula with LaTeX and convert glyphs to SVG paths."""
    font_package = r"\usepackage{lmodern}" if latin_modern else ""
    source = rf"""
\documentclass[border=0.6pt]{{standalone}}
{font_package}
\usepackage{{amsmath,amssymb,xcolor}}
\definecolor{{FormulaInk}}{{HTML}}{{17211E}}
\begin{{document}}
\color{{FormulaInk}}
${formula}$
\end{{document}}
""".strip()

    with tempfile.TemporaryDirectory(prefix="homepage-formula-") as directory:
        temporary = Path(directory)
        tex_path = temporary / "formula.tex"
        tex_path.write_text(source, encoding="utf-8")
        subprocess.run(
            [
                "latex",
                "-interaction=nonstopmode",
                "-halt-on-error",
                tex_path.name,
            ],
            cwd=temporary,
            check=True,
            capture_output=True,
            text=True,
        )
        subprocess.run(
            [
                "dvisvgm",
                "--no-fonts",
                "--exact",
                "--bbox=min",
                f"--output={ASSETS / filename}",
                "formula.dvi",
            ],
            cwd=temporary,
            check=True,
            capture_output=True,
            text=True,
        )


def render_formulas() -> None:
    """Render project-specific formulas in their manuscript font families."""
    render_formula_svg(
        "formula-crouzeix-bound.svg",
        r"\begin{gathered}"
        r"W(A)=\{x^*Ax:x\in\mathbb C^n,\ \lVert x\rVert_2=1\},\\[3pt]"
        r"\lVert p(A)\rVert"
        r"\leq 2\max_{z\in W(A)}\lvert p(z)\rvert,"
        r"\quad A\in\mathbb C^{n\times n},\ p\in\mathbb C[z]"
        r"\end{gathered}",
        latin_modern=False,
    )
    render_formula_svg(
        "formula-hatano-definitions.svg",
        r"\begin{gathered}"
        r"A_n(a)=\operatorname{tridiag}(a,0,1),\quad"
        r"0<a<1,\quad n\geq2,\quad\varepsilon>0,\\[3pt]"
        r"I_n^{\mathrm{sp}}"
        r"=\left[-2\sqrt a\cos\frac{\pi}{n+1},"
        r"2\sqrt a\cos\frac{\pi}{n+1}\right],\\[3pt]"
        r"\sigma_\varepsilon(A_n)"
        r"=\{z\in\mathbb C:s_{\min}(zI_n-A_n)<\varepsilon\},\\[3pt]"
        r"\gamma_n=\max_{x\in I_n^{\mathrm{sp}}}"
        r"s_{\min}(xI_n-A_n)"
        r"\end{gathered}",
        latin_modern=True,
    )
    render_formula_svg(
        "formula-hatano-criterion.svg",
        r"\sigma_\varepsilon(A_n)\ \text{is connected}"
        r"\quad\Longleftrightarrow\quad \varepsilon>\gamma_n",
        latin_modern=True,
    )
    render_formula_svg(
        "formula-hatano-monotonicity.svg",
        r"\gamma_{n+1}<\gamma_n\qquad(n\geq 2)",
        latin_modern=True,
    )
    render_formula_svg(
        "formula-hatano-scale.svg",
        r"\gamma_n\asymp_a(n+1)a^{n/2}",
        latin_modern=True,
    )


def write_manifest(estimates: dict[str, dict[str, float]]) -> None:
    """Record formulas, numerical parameters, and software versions."""
    manifest = {
        "generator": "scripts/generate_research_figures.py",
        "software": {
            "numpy": np.__version__,
            "scipy": scipy.__version__,
            "matplotlib": mpl.__version__,
            "python": platform.python_version(),
            "text_renderer": "LaTeX via Matplotlib usetex",
        },
        "displayed_formulas": {
            "formula-crouzeix-bound.svg": {
                "font": "Computer Modern",
                "tex": (
                    r"W(A)=\{x^*Ax:x\in\mathbb C^n,"
                    r"\lVert x\rVert_2=1\}; "
                    r"\lVert p(A)\rVert"
                    r"\leq 2\max_{z\in W(A)}\lvert p(z)\rvert; "
                    r"A\in\mathbb C^{n\times n}; p\in\mathbb C[z]"
                ),
            },
            "formula-hatano-definitions.svg": {
                "font": "Latin Modern",
                "tex": (
                    r"A_n(a)=\operatorname{tridiag}(a,0,1); "
                    r"0<a<1; n\geq2; \varepsilon>0; "
                    r"I_n^{\mathrm{sp}}"
                    r"=[-2\sqrt a\cos(\pi/(n+1)),"
                    r"2\sqrt a\cos(\pi/(n+1))]; "
                    r"\sigma_\varepsilon(A_n)"
                    r"=\{z\in\mathbb C:s_{\min}(zI_n-A_n)<\varepsilon\}; "
                    r"\gamma_n=\max_{x\in I_n^{\mathrm{sp}}}"
                    r"s_{\min}(xI_n-A_n)"
                ),
            },
            "formula-hatano-criterion.svg": {
                "font": "Latin Modern",
                "tex": (
                    r"\sigma_\varepsilon(A_n)\ \text{is connected}"
                    r"\Longleftrightarrow \varepsilon>\gamma_n"
                ),
            },
            "formula-hatano-monotonicity.svg": {
                "font": "Latin Modern",
                "tex": r"\gamma_{n+1}<\gamma_n\ (n\geq2)",
            },
            "formula-hatano-scale.svg": {
                "font": "Latin Modern",
                "tex": r"\gamma_n\asymp_a(n+1)a^{n/2}",
            },
        },
        "crouzeix_sharpness": {
            "matrix": [[0, 2], [0, 0]],
            "polynomial": "p(z)=z",
            "numerical_range_boundary": "z(theta)=exp(i theta), 0 <= theta <= 2 pi",
            "boundary_samples": int(theta_sample_count()),
            "font": "Computer Modern",
            "source": (
                "CrouzeixConjecture/AnnMath/"
                "the_numerical_range_is_a_2_spectral_set.tex, "
                "equation eq:sharp-example"
            ),
        },
        "hatano_nelson_transition": {
            "matrix": "A_n(a)=tridiag(a,0,1)",
            "a": A_VALUE,
            "epsilon": EPSILON,
            "n": [6, 7],
            "grid": {
                "real": {
                    "min": float(GRID_X[0]),
                    "max": float(GRID_X[-1]),
                    "points": int(GRID_X.size),
                },
                "imaginary": {
                    "min": float(GRID_Y[0]),
                    "max": float(GRID_Y[-1]),
                    "points": int(GRID_Y.size),
                },
            },
            "method": "Direct float64 SVD of z I_n - A_n(a) at every grid point",
            "gamma_method": "Gapwise scan followed by bounded scalar optimization",
            "gamma_estimates": estimates,
            "font": "Latin Modern",
            "source": (
                "Hatano-Nelson/JPA/JPA_submission_bundle/"
                "exact_connectedness_threshold_hatano_nelson.tex, "
                "equations eq:main-definitions and eq:connected-iff-gamma"
            ),
            "scope_note": (
                "The float64 computations are not interval-certified. "
                "The contours and gamma values are numerical illustrations "
                "and are not used as proof of the manuscript theorem."
            ),
        },
    }
    (ASSETS / "figure-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def theta_sample_count() -> int:
    """Return the number of uniform samples used for the unit-circle raster."""
    return 1201


def main() -> None:
    crouzeix_sharpness_figure()
    estimates = hatano_transition_figure()
    render_formulas()
    write_manifest(estimates)
    print("Generated research figures, formula SVGs, and figure-manifest.json")


if __name__ == "__main__":
    main()
